name: iPhoneOS-SDK

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
      - run: |
          mkdir -p xcode
          cd xcode
          ls /Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
          sudo tar cvf Xcode_13.4.1.tar /Applications/Xcode_13.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
          sudo tar cvf Xcode_13.4.tar /Applications/Xcode_13.4.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
          sudo tar cvf Xcode_13.3.1.tar /Applications/Xcode_13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs
      - name: Upload release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: xcode/*.tar
          tag: v1.0
          file_glob: true
